apiVersion: apps/v1
kind: Deployment
metadata:
  name: meetup-deployment
  labels:
    app: meetup
spec:
  replicas: 1
  selector:
    matchLabels:
      app: meetup
  template:
    metadata:
      labels:
        app: meetup
    spec:
      containers:
        - name: meetup
          image:
          ports:
            - containerPort: 80